

export const SET_TYPE_USER = 'SET_TYPE_USER';
export const SET_PROFILE = 'SET_PROFILE';
export const SOMEONE_IN_SYSTEM = 'SOMEONE_IN_SYSTEM';
export const LOG_OUT = 'LOG_OUT';
export const UPDATE_RESUMES = 'UPDATE_RESUMES';
export const UPDATE_VACANCIES = 'UPDATE_VACANCIES';
export const PICK_ID = 'PICK_ID';
export const UPDATE_VACANCIES_AFTER_DELETE = 'UPDATE_VACANCIES_AFTER_DELETE';
export const UPDATE_RESUMES_AFTER_DELETE = 'UPDATE_RESUMES_AFTER_DELETE';
export const SET_TOTAL_RESUMES = 'SET_TOTAL_RESUMES';
export const SET_TOTAL_VACANCIES = 'SET_TOTAL_VACANCIES';
export const SET_SEARCH_SETTINGS = 'SET_SEARCH_SETTINGS';
